gui:
  shortTimeFormat: 15:04
  border: single
  nerdFontsVersion: "3"
  spinner:
    frames: ["◜", "◠", "◝", "◞", "◡", "◟"]
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
notARepository: 'skip'
