# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"


[templates]
defer = """
{{ hooks?.pre | nl }}
{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}
{{ hooks?.post | nl }}
"""
# for debugging:
echo_file = """
{{ hooks?.pre | nl }}
{% for file in files %}
echo file = "{{ file }}"
{% endfor %}
{{ hooks?.post | nl }}
"""


[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.ez-compinit]
github = "mattmc3/ez-compinit"
[plugins.ez-compinit.hooks]
pre = """
zstyle ':plugin:ez-compinit' 'compstyle' 'prez'
zstyle ':plugin:ez-compinit' 'use-cache' 'yes'
zstyle ':completion:*' 'use-cache' 'yes'
"""

[plugins.omz-gitfast]
# TODO: completion without this plugin is actually better. not sure how much slower on large-ish repos
github = "ohmyzsh/ohmyzsh"
dir = "plugins/gitfast"
apply = ["fpath"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]
